# Site settings
title: MAYDAY.US
email: info@mayone.us
description: "MAYDAY.US - A Crowdfunded, Kickstarted SuperPAC to end all SuperPACs"
baseurl: ''

# Build settings
encoding: utf-8
markdown: kramdown
permalink: pretty

# Blog & RSS settings
name: Mayday PAC Blog
url: https://mayday.us
